# Generated by Django 4.1.1 on 2023-06-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_alter_usersettings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('people', models.CharField(choices=[('1', 'one person'), ('2', 'two people'), ('3', 'three people'), ('4', 'four people'), ('5', 'five  people')], default='1', max_length=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
