# Generated by Django 4.1.1 on 2023-04-01 09:34

from django.db import migrations, models
import django.db.models.deletion
import services.file_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=services.file_module.models.get_file_path, verbose_name='File')),
                ('object_id', models.PositiveIntegerField(db_index=True, null=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
