# Generated by Django 4.1.1 on 2023-06-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0003_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='products_module.category', verbose_name='Category'),
        ),
    ]
